# Generated by Django 5.2.4 on 2026-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_image',
            field=models.URLField(blank=True),
        ),
    ]
